# Generated by Django 4.2.25 on 2025-11-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=25)),
                ('employee_id', models.BigIntegerField()),
                ('department', models.CharField(max_length=225)),
                ('log_in', models.DateTimeField()),
                ('log_out', models.DateTimeField()),
            ],
        ),
    ]
