# Generated by Django 4.2.25 on 2025-11-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_api_data'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='api_data',
            table='api_data',
        ),
    ]
