# Generated by Django 3.2.25 on 2025-05-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20250515_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('location', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
