# Generated by Django 3.2.25 on 2025-05-17 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.company'),
            preserve_default=False,
        ),
    ]
